---
- name: Configurar e deploy da aplicação
  hosts: web
  become: true

  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes
        upgrade: yes

    - name: Instalar pacotes essenciais
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Clonar o projeto da aplicação
      git:
        repo: https://github.com/usuario/seu-projeto.git
        dest: /home/ubuntu/app
        version: main
        force: yes

    - name: Subir aplicação com Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /home/ubuntu/app
