---
- name: Configurar VM e fazer deploy da aplicação
  hosts: all
  become: true
  vars:
    ansible_ssh_private_key_file: "/home/ubuntu/.ssh/id_rsa" 
  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes
        upgrade: yes

    - name: Instalar Docker e Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Clonar repositório do projeto
      git:
        repo: https://github.com/Party-Chinese-Comunism/terraform-repo.git
        dest: /home/ubuntu/app
        version: main
        force: yes

    - name: Subir containers com Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /home/ubuntu/app
