name: CI/CD Pipeline for Terraform and Ansible
on:
  push:
    branches:
      - lucas

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    outputs:
      vm_ip: ${{ steps.apply.outputs.vm_ip }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up GCP credentials (from base64)
        run: |
          mkdir -p /home/runner/gcp_credentials
          echo "${{ secrets.GCP_CREDENTIALS_BASE64 }}" | base64 -d > /home/runner/gcp_credentials/credentials.json
          chmod 600 /home/runner/gcp_credentials/credentials.json
          head -n 5 /home/runner/gcp_credentials/credentials.json
          
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          
      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init
          
      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -out=planfile \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "region=${{ secrets.GCP_REGION }}" \
            -var "zone=${{ secrets.GCP_ZONE }}" \
            -var "credentials_file_path=/home/runner/gcp_credentials/credentials.json" \
            -var "public_key_path=/home/runner/.ssh/id_rsa.pub"
            
      - name: Terraform Apply and extract VM IP
        id: apply
        run: |
          cd terraform
          terraform apply -auto-approve planfile
          
          # Capturar a saída completa e extrair apenas o IP
          TERRAFORM_OUTPUT=$(terraform output vm_ip)
          NEW_VM_IP=$(echo "$TERRAFORM_OUTPUT" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')
          
          # Usar GITHUB_OUTPUT para disponibilizar para outros jobs
          echo "vm_ip=$NEW_VM_IP" >> $GITHUB_OUTPUT
          echo "Novo IP da VM: $NEW_VM_IP"
          
      - name: Debug IP da VM
        run: echo "IP da VM é ${{ steps.apply.outputs.vm_ip }}"

  ansible-configure:
    runs-on: ubuntu-latest
    needs: terraform-deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub
          
      - name: Debug IP da VM recebido
        run: echo "IP da VM recebido do job anterior ${{ needs.terraform-deploy.outputs.vm_ip }}"
        
      - name: Set up Ansible and SSH
        run: |
          set -e
          
          NEW_VM_IP="${{ needs.terraform-deploy.outputs.vm_ip }}"
          
          # Verificar se temos um IP válido
          if [[ -z "$NEW_VM_IP" ]] || [[ ! "$NEW_VM_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Erro: NEW_VM_IP não contém um IP válido: '$NEW_VM_IP'"
            exit 1
          fi
          
          echo "Usando IP da VM: $NEW_VM_IP"
          
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ansible sshpass
          if ! command -v ansible >/dev/null; then
            echo "Erro: Ansible não instalado"
            exit 1
          fi
          
          # Adicionar IP ao known_hosts
          echo "Adicionando $NEW_VM_IP ao known_hosts..."
          ssh-keyscan -H "$NEW_VM_IP" >> ~/.ssh/known_hosts
          
      - name: Run Ansible Playbook with SSH Key
        run: |
          cd ansible
          ansible-playbook playbook.yml \
            --user=ubuntu \
            --private-key=~/.ssh/id_rsa \
            -i "${{ needs.terraform-deploy.outputs.vm_ip }},"
