name: CI/CD Pipeline for Terraform and Ansible

on:
  push:
    branches:
      - lucas

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Atualizado para versão mais recente

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Versão mais recente
        with:
          terraform_version: "1.12.1"

      - name: Set up GCP credentials
        run: |
          mkdir -p /home/runner/gcp_credentials
          echo "${{ secrets.GCP_CREDENTIALS }}" > /home/runner/gcp_credentials/credentials.json
          chmod 644 /home/runner/gcp_credentials/credentials.json
          ls -la /home/runner/gcp_credentials/  # Verificação

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply and get VM IP
        id: apply
        run: |
          cd terraform
          terraform apply -auto-approve \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "region=${{ secrets.GCP_REGION }}" \
            -var "zone=${{ secrets.GCP_ZONE }}" \
            -var "credentials_file_path=/home/runner/gcp_credentials/credentials.json"
          
          # Captura o IP da VM (ajuste conforme sua output do Terraform)
          terraform output -raw vm_ip > vm_ip.txt

      - name: Update Ansible inventory with the new VM IP
        run: |
          NEW_VM_IP=$(cat terraform/vm_ip.txt)
          echo "Novo IP da VM: $NEW_VM_IP"
          cd ansible
          sed -i "s/<ip_da_vm>/$NEW_VM_IP/" inventory.ini
          cat inventory.ini  # Para verificação no log

      - name: Set up Ansible and SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass
          
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Adiciona o host ao known_hosts para evitar prompt
          ssh-keyscan -H $(cat terraform/vm_ip.txt) >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.ini playbook.yml --user=ubuntu --private-key=~/.ssh/id_rsa
