name: CI/CD Pipeline for Terraform and Ansible

on:
  push:
    branches:
      - lucas

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.12.1"

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Set GOOGLE_APPLICATION_CREDENTIALS environment variable
        run: |
          # Grava o conteúdo do Secret diretamente no ambiente como uma variável
          echo "${{ secrets.GCP_CREDENTIALS }}" > $HOME/gcp_credentials.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp_credentials.json

      - name: Terraform Apply and get VM IP
        id: apply
        run: |
          cd terraform
          cat /home/runner/gcp_credentials/credentials.json
          terraform apply -auto-approve \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "region=${{ secrets.GCP_REGION }}" \
            -var "zone=${{ secrets.GCP_ZONE }}"

      - name: Update Ansible inventory with the new VM IP
        run: |
          NEW_VM_IP=$(cat vm_ip.txt)
          cd ansible
          sed -i "s/<ip_da_vm>/$NEW_VM_IP/" inventory.ini

      - name: Set up Ansible
        run: |
          sudo apt-get install -y ansible
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.ini playbook.yml
        env:
          ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
