name: CI/CD Pipeline for Terraform and Ansible

on:
  push:
    branches:
      - lucas
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.0"

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply and get VM IP
        id: apply
        run: |
          cd terraform
          echo "${{ secrets.GCP_CREDENTIALS_FILE }}" > ~/gcp_credentials.json
          terraform apply -auto-approve \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "region=${{ secrets.GCP_REGION }}" \
            -var "zone=${{ secrets.GCP_ZONE }}" \
            -var "credentials_file_path=~/gcp_credentials.json"
          echo "VM IP is $(terraform output -raw vm_ip)" > vm_ip.txt

      - name: Update Ansible inventory with the new VM IP
        run: |
          NEW_VM_IP=$(cat vm_ip.txt)
          cd ansible
          sed -i "s/<ip_da_vm>/$NEW_VM_IP/" inventory.ini

      - name: Set up Ansible
        run: |
          sudo apt-get install -y ansible
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.ini playbook.yml
        env:
          ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
