name: CI/CD Pipeline for Terraform and Ansible

on:
  push:
    branches:
      - lucas

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GCP credentials (from base64)
        run: |
          mkdir -p /home/runner/gcp_credentials
          echo "${{ secrets.GCP_CREDENTIALS_BASE64 }}" | base64 -d > /home/runner/gcp_credentials/credentials.json
          chmod 600 /home/runner/gcp_credentials/credentials.json
          head -n 5 /home/runner/gcp_credentials/credentials.json

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -out=planfile \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "region=${{ secrets.GCP_REGION }}" \
            -var "zone=${{ secrets.GCP_ZONE }}" \
            -var "credentials_file_path=/home/runner/gcp_credentials/credentials.json" \
            -var "public_key_path=~/.ssh/id_rsa.pub"

      - name: Terraform Apply and extract VM IP
        run: |
          cd terraform
          terraform apply -auto-approve planfile
          terraform output -raw vm_ip > vm_ip.txt

      - name: Debug IP da VM
        run: |
          VM_IP=$(cat terraform/vm_ip.txt | tr -d '\r')
          echo "IP da VM é $VM_IP"

      - name: Set up Ansible and SSH
        run: |
          set -e
          VM_IP=$(cat terraform/vm_ip.txt | tr -d '\r')

          sudo apt-get clean
          sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/ubuntu.list"

          set +e
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ansible sshpass --fix-missing
          EXIT_CODE=$?
          set -e

          if [ "$EXIT_CODE" -ne 0 ] && [ "$EXIT_CODE" -ne 1 ]; then
            echo "Erro grave na instalação (código $EXIT_CODE)"
            exit "$EXIT_CODE"
          fi

          if ! command -v ansible >/dev/null; then
            echo "Erro: Ansible não foi instalado corretamente"
            exit 1
          fi

          echo "Adicionando $VM_IP ao known_hosts..."
          ssh-keyscan -H "$VM_IP" >> ~/.ssh/known_hosts
          true

      - name: Run Ansible Playbook without inventory file
        run: |
          VM_IP=$(cat terraform/vm_ip.txt | tr -d '\r')
          cd ansible
          ansible-playbook playbook.yml --user=ubuntu --private-key=~/.ssh/id_rsa -i "$VM_IP,"
