name: CI/CD Pipeline for Terraform and Ansible

on:
  push:
    branches:
      - lucas

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GCP credentials (from base64)
        run: |
          mkdir -p /home/runner/gcp_credentials
          echo "${{ secrets.GCP_CREDENTIALS_BASE64 }}" | base64 -d > /home/runner/gcp_credentials/credentials.json
          chmod 600 /home/runner/gcp_credentials/credentials.json

      - name: Set up gcloud and get GKE credentials 
        run: |
          gcloud auth activate-service-account --key-file=/home/runner/gcp_credentials/credentials.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud container clusters get-credentials $CLUSTER_NAME --region ${{ secrets.GCP_REGION }}

      - name: Download Kubernetes manifests from GCS
        run: |
          mkdir -p k8s-manifests
          gsutil -m cp -r gs://blog-iris-hml/manifests/* ./k8s-manifests

      - name: Apply manifests to cluster
        run: |
          kubectl apply -f ./k8s-manifests
