name: Provision GKE Cluster and Deploy Manifests

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGION: ${{ secrets.GCP_REGION_HML }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GCP credentials (from base64)
        run: |
          mkdir -p /home/runner/gcp_credentials
          echo "${{ secrets.GCP_CREDENTIALS_BASE64 }}" | base64 -d > /home/runner/gcp_credentials/credentials.json
          chmod 600 /home/runner/gcp_credentials/credentials.json

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -out=planfile \
            -var "project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "region=us-central1" \
            -var "zone=us-central1-a" \
            -var "credentials_file_path=/home/runner/gcp_credentials/credentials.json"
            -var "machine_type=e2-medium" \
            -var "image=ubuntu-os-cloud/ubuntu-2204-lts" \
            -var "cluster_size=1" \
            -var "cluster_name=stage" \

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve planfile
          CLUSTER_NAME=$(terraform output -raw cluster_name | tr -d '\r')
          echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV
          
      - name: Configurar acesso kubectl
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials stage --region us-central1 --project ${{ secrets.GCP_PROJECT_ID_STAGE }}

      - name: Mostrar serviços monitoring
        run: |
          kubectl get svc -n monitoring


    
